# Generated by Django 5.1.7 on 2025-03-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='firebase_token',
            field=models.CharField(max_length=255),
        ),
    ]
