# Generated by Django 5.1.7 on 2025-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fcmtoken_created_at_fcmtoken_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
