# Generated by Django 5.1.7 on 2025-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fcmtoken_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'verbose_name': 'FCM Token', 'verbose_name_plural': 'FCM Tokens'},
        ),
    ]
